# -*- coding: utf-8 -*-
"""MLcollege.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a0m6kklL4sVVkCHnhXD4GhnZTYklTBS5
"""

#!pip install streamlit_lottie

#!pip install streamlit
import streamlit as st
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import euclidean_distances
from streamlit_lottie import st_lottie
import requests
import json

st.set_page_config(page_title="Exoplanet Mass Predictor", layout="wide")

# ----------------- Load Animation -----------------
def load_lottie_animation(filepath: str):
    with open(filepath, "r") as file:
        return json.load(file)


# ----------------- Load Data -----------------
@st.cache_data
def load_data():
    df = pd.read_csv("/home/mrutyunjaya/Downloads/Exoplanet with star mass.csv")
    df = df.drop(columns=['Unnamed: 0', 'pl_name', 'hostname']).drop_duplicates()
    return df

# Load animations# Load
lottie_space_intro = load_lottie_animation("/home/mrutyunjaya/Downloads/Animation - 1745037899411.json")
lottie_success = load_lottie_animation("/home/mrutyunjaya/Downloads/Animation - 1745038127530.json")


# ----------------- Page Title -----------------
st_lottie(lottie_space_intro, height=250, key="space_intro")
st.title("🚀 Exoplanet Mass & Similarity Explorer")

# ----------------- Data & Model -----------------
data = load_data()
X = data[['pl_orbper', 'pl_orbsmax', 'st_mass']]
y = data['pl_bmasse']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = RandomForestRegressor(random_state=42)
model.fit(X_scaled, y)

# ----------------- TABS -----------------
tab1, tab2, tab3, tab4 = st.tabs(["🔮 Prediction", "📊 Visualizations", "🪐 Similar Planet", "📄 Dataset"])

# ================= TAB 1: PREDICTION =================
with tab1:
    st.header("🔮 Predict Planet Mass")
    orbper = st.number_input("Orbital Period (days)", min_value=0.0, step=0.1, value=1.0)
    orbsmax = st.number_input("Semi-Major Axis (AU)", min_value=0.0, step=0.01, value=0.01)
    starmass = st.number_input("Star Mass (Solar Mass)", min_value=0.0, step=0.01, value=1.0)

    input_features = np.array([[orbper, orbsmax, starmass]])
    input_scaled = scaler.transform(input_features)
    predicted_mass = model.predict(input_scaled)[0]

    st_lottie(lottie_success, height=150, key="success")
    st.success(f"🌍 Predicted Planet Mass: **{predicted_mass:.2f} Earth masses**")

    earth_mass = 1
    jupiter_mass = 317.8
    if predicted_mass < earth_mass:
        st.info("🟢 Lighter than Earth!")
    elif predicted_mass < jupiter_mass:
        st.info("🟡 Between Earth and Jupiter")
    else:
        st.info("🔴 Heavier than Jupiter! Possibly a gas giant.")

    # Export Prediction
    st.subheader("📥 Export Prediction")
    if st.button("Download Prediction as CSV"):
        pred_df = pd.DataFrame({
            "Orbital Period": [orbper],
            "Semi-Major Axis": [orbsmax],
            "Star Mass": [starmass],
            "Predicted Planet Mass": [predicted_mass]
        })
        st.download_button("Download", pred_df.to_csv(index=False), file_name="prediction.csv")

# ================= TAB 2: VISUALIZATIONS =================
with tab2:
    st.header("📊 Explore the Dataset")

    plot_choice = st.selectbox("Choose a Plot", ["Mass Distribution", "Feature Correlation", "Orbital Period vs Mass"])

    if plot_choice == "Mass Distribution":
        fig = px.histogram(data, x='pl_bmasse', nbins=30,
                           title="Distribution of Planet Masses",
                           labels={'pl_bmasse': "Planet Mass (Earth Masses)"},
                           color_discrete_sequence=['#4e79a7'])
        st.plotly_chart(fig, use_container_width=True)

    elif plot_choice == "Feature Correlation":
        corr = data.corr()
        fig = px.imshow(corr,
                        text_auto=True,
                        title="Correlation Heatmap",
                        color_continuous_scale="RdBu_r")
        st.plotly_chart(fig, use_container_width=True)

    elif plot_choice == "Orbital Period vs Mass":
        fig = px.scatter(data, x='pl_orbper', y='pl_bmasse',
                         title="Orbital Period vs Planet Mass",
                         labels={'pl_orbper': "Orbital Period (days)", 'pl_bmasse': "Planet Mass (Earth Masses)"},
                         opacity=0.6)
        st.plotly_chart(fig, use_container_width=True)

    # Feature Importance Plot
    st.subheader("🔍 Feature Importance")
    importances = model.feature_importances_
    feature_names = X.columns
    fig = px.bar(x=feature_names, y=importances,
                 labels={'x': 'Feature', 'y': 'Importance'},
                 title="Which Features Influence Mass Prediction?")
    st.plotly_chart(fig, use_container_width=True)

# ================= TAB 3: SIMILAR PLANET =================
with tab3:
    st.header("🪐 Find a Similar Known Exoplanet")

    distances = euclidean_distances(X_scaled, input_scaled)
    nearest_index = np.argmin(distances)
    similar_planet = data.iloc[nearest_index]

    st.write("Most similar known planet:")
    st.dataframe(similar_planet.to_frame().T)

# ================= TAB 4: DATASET =================
with tab4:
    st.header("📄 Dataset Preview")
    st.dataframe(data)




